[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: запускает все UI автотесты.
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    smoke: Маркировка для smoke тестов.
    slow: Маркировка для slow тестов.
    critical: Маркировка для critical тестов.
    authorization: Маркировка для authorization тестов.
    courses: для тестов, связанных с курсами.
    regression: для регрессионных тестов.